
	module anacondapy/5.3.1 loaded.
	5.3.1 contains an old version of the conda command.
	Use 'source activate' not 'conda activate' or you will get an error.
	Newer modules with the YYYY.MM version format do not have this problem.

Traceback (most recent call last):
  File "/usr/people/qiongz/.conda/envs/myenv/lib/python3.5/site-packages/bayes_opt/target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (0.47531980423231657, 0.7482920440979423, 0.0005718740867244332, 0.30233257263183977, 1.4675589081711304, 0.7308464869219945, 1.0126750357505876)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/people/qiongz/submisions/optimalfreerecall/CMR_prob/script_fitCMRprob.py", line 59, in <module>
    main()
  File "/usr/people/qiongz/submisions/optimalfreerecall/CMR_prob/script_fitCMRprob.py", line 54, in main
    n_iter = 200, # number of evaluations using bayesian optimization
  File "/usr/people/qiongz/.conda/envs/myenv/lib/python3.5/site-packages/bayes_opt/bayesian_optimization.py", line 174, in maximize
    self.probe(x_probe, lazy=False)
  File "/usr/people/qiongz/.conda/envs/myenv/lib/python3.5/site-packages/bayes_opt/bayesian_optimization.py", line 112, in probe
    self._space.probe(params)
  File "/usr/people/qiongz/.conda/envs/myenv/lib/python3.5/site-packages/bayes_opt/target_space.py", line 194, in probe
    target = self.target_func(**params)
  File "/mnt/bucket/people/qiongz/submisions/optimalfreerecall/CMR_prob/fitpatterns_opt_drift.py", line 427, in obj_func_prob
    N, ll, lag_examine,data_id = set_parameter_prob()
  File "/mnt/bucket/people/qiongz/submisions/optimalfreerecall/CMR_prob/fitpatterns_opt_drift.py", line 29, in set_parameter_prob
    ll = lls[data_id]
IndexError: list index out of range
